# Generated by Django 5.0.9 on 2026-09-23 19:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('shipping_fee_dhaka', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=10)),
                ('shipping_fee_other', models.DecimalField(decimal_places=2, default=Decimal('120.00'), max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_code', models.CharField(default='BDT', max_length=8)),
                ('currency_symbol', models.CharField(default='৳', max_length=8)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('support_phone', models.CharField(blank=True, max_length=40)),
                ('payout_minimum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('site_name', models.CharField(default='ShopHaat', max_length=120)),
                ('site_tagline', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        # Ensure the singleton row exists on every environment that runs
        # this migration. Idempotent — get_or_create makes re-runs a no-op.
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model("marketplace", "PlatformSettings").objects.get_or_create(pk=1),
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
