import { useEffect, useState } from "react";
import { FaDollarSign, FaMoneyBillWave, FaPiggyBank, FaHourglassHalf } from "react-icons/fa";

import { Breadcrumbs } from "../../components/common/Breadcrumbs";
import { EmptyState } from "../../components/common/EmptyState";
import { ErrorState } from "../../components/common/ErrorState";
import { Money } from "../../components/common/Money";
import { Skeleton } from "../../components/common/Skeleton";
import { StatCard } from "../../components/admin/StatCard";
import { useToast } from "../../hooks/useToast";
import { extractErrorMessage } from "../../services/apiClient";
import {
  fetchSellerEarnings,
  fetchSellerSettlements,
} from "../../services/marketplaceService";

/**
 * Seller earnings + settlements. Surfaces gross sales, commission taken,
 * net earnings, and what's already been paid out vs still pending. Also
 * lists settlement periods as a quick audit.
 */
export function SellerEarningsPage() {
  const { showToast } = useToast();
  const [summary, setSummary] = useState(null);
  const [settlements, setSettlements] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    Promise.all([fetchSellerEarnings(), fetchSellerSettlements()])
      .then(([e, s]) => {
        if (cancelled) return;
        setSummary(e);
        setSettlements(s || []);
      })
      .catch((err) => {
        if (cancelled) return;
        setError(extractErrorMessage(err, "Could not load earnings."));
        showToast({ type: "error", message: extractErrorMessage(err, "Could not load earnings.") });
      })
      .finally(() => !cancelled && setLoading(false));
    return () => {
      cancelled = true;
    };
  }, [showToast]);

  if (loading) {
    return (
      <div className="space-y-3">
        <Skeleton className="h-8 w-1/3" />
        <Skeleton className="h-32 w-full" />
        <Skeleton className="h-64 w-full" />
      </div>
    );
  }

  if (error) return <ErrorState title="Could not load" description={error} />;
  if (!summary) return null;

  return (
    <div>
      <Breadcrumbs
        items={[
          { label: "Seller Center", to: "/seller" },
          { label: "Earnings" },
        ]}
        className="mb-3"
      />
      <h1 className="mb-4 text-xl font-bold text-text-primary">Earnings &amp; settlements</h1>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <StatCard
          icon={FaDollarSign}
          label="Gross Sales"
          value={<Money amount={summary.total_sales} />}
          accent="text-state-info"
        />
        <StatCard
          icon={FaMoneyBillWave}
          label="Marketplace Commission"
          value={<Money amount={summary.marketplace_commission} />}
          accent="text-state-danger"
        />
        <StatCard
          icon={FaPiggyBank}
          label="Net Earnings"
          value={<Money amount={summary.net_earnings} />}
          accent="text-state-success"
        />
        <StatCard
          icon={FaHourglassHalf}
          label="Pending Payout"
          value={<Money amount={summary.pending_settlement} />}
          accent="text-state-warning"
        />
      </div>

      <section className="mt-6 rounded-xl border border-border-subtle bg-surface-card shadow-card">
        <header className="border-b border-border-subtle px-4 py-3">
          <h2 className="text-base font-bold text-text-primary">Settlement periods</h2>
          <p className="text-xs text-text-secondary">
            Total paid out so far: <Money amount={summary.paid_settlement} className="font-semibold" />
          </p>
        </header>
        {settlements.length === 0 ? (
          <EmptyState
            title="No settlements yet"
            description="Settlements are generated by the marketplace admin periodically."
          />
        ) : (
          <table className="w-full text-sm">
            <thead className="bg-canvas-elevated text-left text-xs uppercase tracking-wider text-text-secondary">
              <tr>
                <th className="px-4 py-3">Period</th>
                <th className="px-4 py-3">Orders</th>
                <th className="px-4 py-3 text-right">Gross</th>
                <th className="px-4 py-3 text-right">Commission</th>
                <th className="px-4 py-3 text-right">Net</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Paid on</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border-subtle">
              {settlements.map((s) => (
                <tr key={s.id} className="hover:bg-canvas-elevated/50">
                  <td className="px-4 py-3 text-xs font-semibold text-text-primary">
                    {s.period_start} → {s.period_end}
                  </td>
                  <td className="px-4 py-3 text-text-secondary">{s.seller_orders_count ?? "—"}</td>
                  <td className="px-4 py-3 text-right text-text-primary"><Money amount={s.gross_amount} /></td>
                  <td className="px-4 py-3 text-right text-state-danger">
                    <Money amount={s.commission_amount} />
                  </td>
                  <td className="px-4 py-3 text-right font-semibold text-text-primary">
                    <Money amount={s.net_amount} />
                  </td>
                  <td className="px-4 py-3">
                    <span className="rounded-full bg-state-info/15 px-2 py-0.5 text-xs font-semibold text-state-info">
                      {s.status}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-xs text-text-secondary">
                    {s.paid_at ? new Date(s.paid_at).toLocaleDateString() : "—"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>
    </div>
  );
}
