# Generated by Django 5.0.9 on 2026-09-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('orders', '0002_remove_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='marketplace.sellerorder'),
        ),
    ]
