# Generated by Django 5.0.9 on 2026-09-14 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage_image_url_alter_productimage_image'),
        ('orders', '0002_remove_order_shipping_method'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='delivery_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='delivery_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('seller_rating__isnull', True), models.Q(('seller_rating__gte', 1), ('seller_rating__lte', 5)), _connector='OR'), name='seller_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('delivery_rating__isnull', True), models.Q(('delivery_rating__gte', 1), ('delivery_rating__lte', 5)), _connector='OR'), name='delivery_rating_range'),
        ),
    ]
